backend:
  name: github
  repo: christophermartino/hugo-restaurant-tutorial
  branch: master
media_folder: src/img/gallery
collections:
  - name: 'food'
    label: 'Food Item'
    folder: 'site/content/food'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Name of Item', name: 'title', widget: 'string' }
      - { label: 'Supported Meals', name: 'categories', widget: 'list', default: ['lunch', 'dinner'] }
      - { label: 'Ingredients/Description', name: 'description', widget: 'text' }
      - { label: 'Type of Food', name: 'type', widget: 'string', default: 'raw bar' }
      - { label: 'Price', name: 'price', widget: 'string' }
